# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
  - name: ğŸ™‹  Usage Questions
    url: https://github.com/datateller-org.github.io/discussions
    about: |
      Use Data Teller's GitHub Discussions to ask "How do I do X with Data Teller?".
  - name: ğŸ“–  Tutorial
    url: https://github.com/datateller-org.github.io
    about: |
      The Data Teller tutorial is continually updated and provides an in depth walkthrough
      of how to use the latest release of Data Teller.
  - name: ğŸ“  Data Teller Code of Conduct
    url: https://github.com/datateller-org.github.io/coc/CODE_OF_CONDUCT.md
    about: Expectations for how people will interact with each other on Data Teller's GitHub.
